/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE fmailyBaseService PLEASE EDIT ../fmaily.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Fmaily } from '../../domain/molsa_db/fmaily';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../fmaily.service.ts
 */

/*
 * SCHEMA DB fmaily
 *
	{
		date: {
			type: 'Date'
		},
		fname: {
			type: 'String'
		},
		fsurname: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		fmaily: {
			type: Schema.ObjectId,
			ref : "Staff"
		},
	}
 *
 */
@Injectable()
export class FmailyBaseService {

    contextUrl: string = environment.endpoint + '/fmaily';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * fmailyService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Fmaily): Observable<Fmaily> {
        return this.http
            .post<Fmaily>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * fmailyService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * fmailyService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Fmaily> {
        return this.http
            .get<Fmaily>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * fmailyService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Fmaily[]> {
        return this.http
            .get<Fmaily[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * fmailyService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Fmaily): Observable<Fmaily> {
        return this.http
            .post<Fmaily>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
