/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE staffBaseService PLEASE EDIT ../staff.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Staff } from '../../domain/molsa_db/staff';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Staff.service.ts
 */

/*
 * SCHEMA DB Staff
 *
	{
		fmailyID: {
			type: 'Integer'
		},
		name: {
			type: 'String'
		},
		surename: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		fmaily: {
			type: Schema.ObjectId,
			ref : "Staff"
		},
	}
 *
 */
@Injectable()
export class StaffBaseService {

    contextUrl: string = environment.endpoint + '/staff';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * StaffService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Staff): Observable<Staff> {
        return this.http
            .post<Staff>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * StaffService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * StaffService.findByfmaily
    *   @description CRUD ACTION findByfmaily
    *   @param Objectid key Id of model to search for
    *
    */
    findByFmaily(id: string): Observable<Staff[]> {
        return this.http
            .get<Staff[]>(this.contextUrl + '/findByfmaily/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * StaffService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Staff> {
        return this.http
            .get<Staff>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * StaffService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Staff[]> {
        return this.http
            .get<Staff[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * StaffService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Staff): Observable<Staff> {
        return this.http
            .post<Staff>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
